### ISSUE TITLE
instances of efficiency mode not doing a free chord

### ISSUE THREAD

**Issue by hanshansenrl** [DavidNHill/JSMinesweeper#3]
might be related to that last update?

ive encountered this several times now.

reproducible if u recreate the board in the img (web js version)

sorry if this is not a bug but an efficiency trick i do not know about...
edit: yea i think it only does that if it is 100% sure clicking then chording is definitely not gonna take more clicks...i still think these are new occurences and haven't appeared until recently.
![chrome_2021-07-04_02-38-15](https://user-images.githubusercontent.com/46114067/135043237-dd3d6d29-74ec-49ed-96c9-d4094072c213.png)

**Comment by DavidNHill** [comment]
This is doing what I intended , but I now think it is wrong.

Chording (5,5) immediately gives 2 tiles for 1 click = +1  (expect gain = +1)

What the solver has discovered is that there is a 0.73 chance that (5,6) is a '1'  in which case clearing it and chord it gives 5 tiles for 2 clicks = +3  (expected gain is 0.73 x 3 = 2.19).  If it isn't a '1' then 1 tile for 1 click = 0  which doesn't impact the expected benefit.

What I haven't allowed for is that since (5,6) is adjacent to (5,5) then chording (5,5) (which is +1) is strictly better than playing (5,6) (which is 0).

if (5,6) is '1' ==> +3 x 0.73 = 2.19
if (5,6) not '1' ==> +1 x 0.27  = 0.27
So the expected benefit is now 2.46

I'll look to correct this.

Thank you for the report.

**Comment by DavidNHill** [comment]
I've fixed this and made some other improvements to the efficiency algorithm.  It should play a bit more efficiently now.
